version: '2'

services:
  redis-master:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PASSWORD=my_master_password
      - REDIS_REPLICATION_MODE=master
    ports:
      - '6379:6379'
    volumes:
      - /path/to/your_redis.conf:/opt/bitnami/redis/etc/redis.conf
      - /opt/redis/redis-persistence:/bitnami/redis/data

  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - '6380'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=my_master_password
      - REDIS_PASSWORD=my_slave_password